import React, { useRef } from 'react';
import { Link } from 'react-router-dom';
import { usePageInteractions } from './usePageInteractions';
import img1 from '../assets/Image Apr 29, 2026, 02_58_02 PM.png';
import img2 from '../assets/Image Apr 29, 2026, 12_02_58 PM.png';
import img3 from '../assets/Image Apr 29, 2026, 03_26_01 PM.png';
import img4 from '../assets/Image Apr 29, 2026, 12_11_16 PM.png';
import img5 from '../assets/Image Apr 29, 2026, 03_27_55 PM.png';
import img7 from '../assets/Image Apr 29, 2026, 12_29_28 PM.png';
import img8 from '../assets/Image Apr 29, 2026, 12_31_00 PM.png';
import img9 from '../assets/Image Apr 29, 2026, 12_31_50 PM.png';
import img10 from '../assets/Image Apr 29, 2026, 12_33_34 PM.png';
import img11 from '../assets/Image Apr 29, 2026, 12_35_41 PM.png';
import img12 from '../assets/Image Apr 29, 2026, 12_46_23 PM.png';
import img13 from '../assets/Image Apr 29, 2026, 12_47_53 PM.png';
import img14 from '../assets/Image Apr 29, 2026, 12_49_44 PM.png';

const Products = () => {
    const rootRef = useRef(null);
    usePageInteractions({ rootRef, carouselTitle: 'Our Customers Are Our Success', faqTitle: 'Your Questions, Answered' });
    return (
        <main ref={rootRef}>
            <div className="w-full" id="हीरो सेक्शन">
                <section className="w-full" style={{ marginTop: 'calc(-1 * 96px)', contain: 'layout style paint' }}>
                    <div className="relative" style={{ paddingTop: '96px' }}>
                        <div className="absolute inset-0" style={{ borderRadius: 'inherit', background: '#FFF8E4' }}></div>
                        <div className="relative mx-auto max-w-[1536px] px-6 flex flex-col gap-0 py-8 @desktop:flex-row @desktop:items-stretch" style={{ zIndex: '10' }}>
                            <div style={{ '--bg-color': 'rgba(0%, 0%, 0%, 0.04764)' }} className="bg-(--bg-color) w-full p-6 @tablet:p-8 @desktop:w-1/2 @desktop:shrink-0 @desktop:px-14 @desktop:py-16 rounded-t-3xl @desktop:rounded-t-none @desktop:rounded-l-3xl">
                                <div className="flex h-full flex-col gap-6">
                                    <div className="flex flex-col items-start gap-4">
                                        <h1 id="products-main-title" className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing) !text-black" style={{ '--typography-font-size': 'var(--typography-display-sm-font-size)', '--typography-font-weight': 'var(--typography-display-sm-font-weight)', '--typography-line-height': 'var(--typography-display-sm-line-height)', '--typography-letter-spacing': 'var(--typography-display-sm-letter-spacing)', '--typography-font-family': 'var(--typography-display-sm-font-family)' }}>
                                            High-Quality Electrical Wires & Cables for Every Application
                                        </h1>
                                        <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#fcfcfb' }}>
                                            Explore our range of FR wires, industrial cables, and fire-resistant wiring solutions designed for safety, durability, and long-term performance.
                                        </p>
                                    </div>
                                    <div className="grid grid-cols-1 gap-4 @tablet:flex @tablet:flex-row items-start @tablet:justify-start">
                                        <Link data-slot="button" label="Explore Products" style={{ '--bg-color': '#E8A317', '--hover-bg-color': '#da990f', color: '#000' }} className="inline-flex shrink-0 cursor-pointer items-center justify-center bg-(--bg-color) whitespace-nowrap transition-all outline-none hover:bg-(--hover-bg-color) focus-visible:border-primary-border focus-visible:ring-[3px] focus-visible:ring-primary-interactive-bg disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-error-border aria-invalid:ring-error-interactive-bg [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])] :size-4 border border-(--bg-color) hover:border-(--hover-bg-color) gap-2 px-5 py-2.5 has-[>svg:first-child]:pr-4 has-[>svg:last-child]:pl-4 has-[>svg:only-child]:px-2.5 rounded-3xl" to="#उत्पाद विशेषताएं">
                                            <span className="min-w-0 overflow-hidden text-ellipsis [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-sm-em-font-size)', '--typography-font-weight': 'var(--typography-body-sm-em-font-weight)', '--typography-line-height': 'var(--typography-body-sm-em-line-height)', '--typography-letter-spacing': 'var(--typography-body-sm-em-letter-spacing)', '--typography-font-family': 'var(--typography-body-sm-em-font-family)', color: '#000' }}>Explore Products</span>
                                        </Link>
                                        <Link data-slot="button" label="Request a Quote" style={{ '--bg-color': 'transparent', '--hover-bg-color': '#e0d9c8', '--border-color': '#2f2f29', '--hover-border-color': '#12120d', color: '#12120d', borderColor: '#2f2f29' }} className="inline-flex shrink-0 cursor-pointer items-center justify-center bg-(--bg-color) whitespace-nowrap transition-all outline-none hover:bg-(--hover-bg-color) focus-visible:border-primary-border focus-visible:ring-[3px] focus-visible:ring-primary-interactive-bg disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-error-border aria-invalid:ring-error-interactive-bg [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*=&#x27;size-&#x27;])]:size-4 border border-(--border-color) hover:border-(--hover-border-color) gap-2 px-5 py-2.5 has-[>svg:first-child]:pr-4 has-[>svg:last-child]:pl-4 has-[>svg:only-child]:px-2.5 rounded-3xl" to="/contact">
                                            <span className="min-w-0 overflow-hidden text-ellipsis [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-sm-em-font-size)', '--typography-font-weight': 'var(--typography-body-sm-em-font-weight)', '--typography-line-height': 'var(--typography-body-sm-em-line-height)', '--typography-letter-spacing': 'var(--typography-body-sm-em-letter-spacing)', '--typography-font-family': 'var(--typography-body-sm-em-font-family)', color: '#12120d' }}>Request a Quote</span>
                                        </Link>
                                    </div>
                                </div>
                            </div>
                            <div className="relative aspect-4/3 w-full overflow-hidden @desktop:aspect-auto @desktop:w-1/2 @desktop:shrink-0 rounded-b-3xl @desktop:rounded-b-none @desktop:rounded-r-3xl">
                                <div className="relative h-full w-full overflow-hidden">
                                    <img alt="Electra Wires German Technology" fetchPriority="high" loading="eager" decoding="async" data-nimg="fill" style={{ position: 'absolute', height: '100%', width: '100%', left: '0', top: '0', right: '0', bottom: '0', objectFit: 'cover', objectPosition: '50% 50%', color: 'transparent', transformOrigin: '50% 50%', transform: 'scale(1)' }} sizes="(max-width: 1024px) 100vw, 50vw" src="/hero-product-new.jpg" />
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div className="w-full" id="उत्पाद विशेषताएं">
                <section className="w-full" style={{ contain: 'layout style paint' }}>
                    <div className="relative">
                        <div className="absolute inset-0" style={{ borderRadius: 'inherit', background: '#FFF8E4' }}></div>
                        <div className="relative mx-auto max-w-[1536px] px-6 flex flex-col gap-8 py-16 @tablet:py-24 @tablet:gap-14" style={{ zIndex: '10' }}>
                            <div className="flex flex-col gap-8 @desktop:flex-row @desktop:items-end @desktop:justify-between">
                                <div className="flex flex-col gap-4 @tablet:max-w-2/3 @desktop:max-w-1/2">
                                    <div className="flex items-baseline gap-1">
                                        <div className="flex items-center">
                                            <div className="h-0 w-4 border-t" style={{ borderColor: '#1b1b16' }}></div>
                                        </div>
                                        <span className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-label-md-font-size)', '--typography-font-weight': 'var(--typography-label-md-font-weight)', '--typography-line-height': 'var(--typography-label-md-line-height)', '--typography-letter-spacing': 'var(--typography-label-md-letter-spacing)', '--typography-font-family': 'var(--typography-label-md-font-family)', color: '#1b1b16' }}>Our Premium Electrical Wire Range</span>
                                    </div>
                                    <h2 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-display-sm-font-size)', '--typography-font-weight': 'var(--typography-display-sm-font-weight)', '--typography-line-height': 'var(--typography-display-sm-line-height)', '--typography-letter-spacing': 'var(--typography-display-sm-letter-spacing)', '--typography-font-family': 'var(--typography-display-sm-font-family)', color: '#060603' }}>
                                        Reliable Electrical Wires Engineered for Safety & Performance
                                    </h2>
                                </div>
                                <div className="gap-3 hidden @tablet:flex">
                                    <Link data-slot="button" label="Consult Our Experts" style={{ '--bg-color': '#E8A317', '--hover-bg-color': '#da990f', color: '#000' }} className="inline-flex shrink-0 cursor-pointer items-center justify-center bg-(--bg-color) whitespace-nowrap transition-all outline-none hover:bg-(--hover-bg-color) focus-visible:border-primary-border focus-visible:ring-[3px] focus-visible:ring-primary-interactive-bg disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-error-border aria-invalid:ring-error-interactive-bg [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])] :size-4 border border-(--bg-color) hover:border-(--hover-bg-color) gap-2 px-6 py-3 has-[>svg:first-child]:pr-4 has-[>svg:last-child]:pl-4 has-[>svg:only-child]:px-3 rounded-full" to="/contact">
                                        <span className="min-w-0 overflow-hidden text-ellipsis [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-em-font-size)', '--typography-font-weight': 'var(--typography-body-md-em-font-weight)', '--typography-line-height': 'var(--typography-body-md-em-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-em-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-em-font-family)', color: '#000' }}>Consult Our Experts</span>
                                    </Link>
                                </div>
                            </div>
                            <div className="flex flex-col gap-8">
                                <div className="grid grid-cols-1 @tablet:grid-cols-2 @desktop:grid-cols-3 gap-6 w-full">
                                    <div className="flex flex-col gap-5">
                                        <div className="overflow-hidden rounded-[28px] bg-[#f4efe2]" style={{ aspectRatio: '1535 / 1024' }}>
                                            <img alt="Best FR House Wires in Noida" fetchPriority="auto" loading="lazy" decoding="async" data-nimg="fill" className="h-full w-full object-contain" style={{ width: '100%', height: '100%', objectFit: 'contain', objectPosition: '50% 50%', color: 'transparent' }} sizes="(max-width: 768px) 85vw, (max-width: 1280px) 55vw, 42vw" src={img1} />
                                        </div>
                                        <div className="flex flex-col gap-3 px-1">
                                            <h3 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-heading-sm-font-size)', '--typography-font-weight': 'var(--typography-heading-sm-font-weight)', '--typography-line-height': 'var(--typography-heading-sm-line-height)', '--typography-letter-spacing': 'var(--typography-heading-sm-letter-spacing)', '--typography-font-family': 'var(--typography-heading-sm-font-family)', color: '#060603' }}>Best FR House Wires in Noida</h3>
                                            <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#1b1b16' }}>Premium FR house wires designed for superior fire resistance, durability, and safe electrical performance in modern homes.</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-col gap-5">
                                        <div className="overflow-hidden rounded-[28px] bg-[#f4efe2]" style={{ aspectRatio: '1535 / 1024' }}>
                                            <img alt="Safety First FR-LSH Wires" fetchPriority="auto" loading="lazy" decoding="async" data-nimg="fill" className="h-full w-full object-contain" style={{ width: '100%', height: '100%', objectFit: 'contain', objectPosition: '50% 50%', color: 'transparent' }} sizes="(max-width: 768px) 85vw, (max-width: 1280px) 55vw, 42vw" src={img2} />
                                        </div>
                                        <div className="flex flex-col gap-3 px-1">
                                            <h3 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-heading-sm-font-size)', '--typography-font-weight': 'var(--typography-heading-sm-font-weight)', '--typography-line-height': 'var(--typography-heading-sm-line-height)', '--typography-letter-spacing': 'var(--typography-heading-sm-letter-spacing)', '--typography-font-family': 'var(--typography-heading-sm-font-family)', color: '#060603' }}>Safety First FR-LSH Wires</h3>
                                            <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#1b1b16' }}>Low smoke, zero halogen FR-LSH wires ideal for high-risk environments ensuring maximum safety and minimal toxic emissions.</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-col gap-5">
                                        <div className="overflow-hidden rounded-[28px] bg-[#f4efe2]" style={{ aspectRatio: '1535 / 1024' }}>
                                            <img alt="High-Voltage Multi-Core XLPE Cables" fetchPriority="auto" loading="lazy" decoding="async" data-nimg="fill" className="h-full w-full object-contain" style={{ width: '100%', height: '100%', objectFit: 'contain', objectPosition: '50% 50%', color: 'transparent' }} sizes="(max-width: 768px) 85vw, (max-width: 1280px) 55vw, 42vw" src={img3} />
                                        </div>
                                        <div className="flex flex-col gap-3 px-1">
                                            <h3 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-heading-sm-font-size)', '--typography-font-weight': 'var(--typography-heading-sm-font-weight)', '--typography-line-height': 'var(--typography-heading-sm-line-height)', '--typography-letter-spacing': 'var(--typography-heading-sm-letter-spacing)', '--typography-font-family': 'var(--typography-heading-sm-font-family)', color: '#060603' }}>High-Voltage Multi-Core XLPE Cables</h3>
                                            <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#1b1b16' }}>High-performance XLPE insulated cables engineered for efficient power transmission and long-lasting durability.</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-col gap-5">
                                        <div className="overflow-hidden rounded-[28px] bg-[#f4efe2]" style={{ aspectRatio: '1535 / 1024' }}>
                                            <img alt="Industrial Armoured Power Cables" fetchPriority="auto" loading="lazy" decoding="async" data-nimg="fill" className="h-full w-full object-contain" style={{ width: '100%', height: '100%', objectFit: 'contain', objectPosition: '50% 50%', color: 'transparent' }} sizes="(max-width: 768px) 85vw, (max-width: 1280px) 55vw, 42vw" src={img4} />
                                        </div>
                                        <div className="flex flex-col gap-3 px-1">
                                            <h3 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-heading-sm-font-size)', '--typography-font-weight': 'var(--typography-heading-sm-font-weight)', '--typography-line-height': 'var(--typography-heading-sm-line-height)', '--typography-letter-spacing': 'var(--typography-heading-sm-letter-spacing)', '--typography-font-family': 'var(--typography-heading-sm-font-family)', color: '#060603' }}>Industrial Armoured Power Cables</h3>
                                            <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#1b1b16' }}>Heavy-duty armoured cables designed for industrial applications, offering strong protection and high reliability.</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-col gap-5">
                                        <div className="overflow-hidden rounded-[28px] bg-[#f4efe2]" style={{ aspectRatio: '1535 / 1024' }}>
                                            <img alt="950°C Rated Fire Survival Cable" fetchPriority="auto" loading="lazy" decoding="async" data-nimg="fill" className="h-full w-full object-contain" style={{ width: '100%', height: '100%', objectFit: 'contain', objectPosition: '50% 50%', color: 'transparent' }} sizes="(max-width: 768px) 85vw, (max-width: 1280px) 55vw, 42vw" src={img5} />
                                        </div>
                                        <div className="flex flex-col gap-3 px-1">
                                            <h3 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-heading-sm-font-size)', '--typography-font-weight': 'var(--typography-heading-sm-font-weight)', '--typography-line-height': 'var(--typography-heading-sm-line-height)', '--typography-letter-spacing': 'var(--typography-heading-sm-letter-spacing)', '--typography-font-family': 'var(--typography-heading-sm-font-family)', color: '#060603' }}>950°C Rated Fire Survival Cable</h3>
                                            <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#1b1b16' }}>Fire survival cables built to maintain circuit integrity even under extreme temperatures up to 950°C.</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-col gap-5">
                                        <div className="overflow-hidden rounded-[28px] bg-[#f4efe2]" style={{ aspectRatio: '1535 / 1024' }}>
                                            <img alt="Single Core PVC Insulated Wires" fetchPriority="auto" loading="lazy" decoding="async" data-nimg="fill" className="h-full w-full object-contain" style={{ width: '100%', height: '100%', objectFit: 'contain', objectPosition: '50% 50%', color: 'transparent' }} sizes="(max-width: 768px) 85vw, (max-width: 1280px) 55vw, 42vw" src={img7} />
                                        </div>
                                        <div className="flex flex-col gap-3 px-1">
                                            <h3 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-heading-sm-font-size)', '--typography-font-weight': 'var(--typography-heading-sm-font-weight)', '--typography-line-height': 'var(--typography-heading-sm-line-height)', '--typography-letter-spacing': 'var(--typography-heading-sm-letter-spacing)', '--typography-font-family': 'var(--typography-heading-sm-font-family)', color: '#060603' }}>Single Core PVC Insulated Wires</h3>
                                            <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#1b1b16' }}>High-quality PVC insulated wires suitable for residential wiring with excellent conductivity and safety.</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-col gap-5">
                                        <div className="overflow-hidden rounded-[28px] bg-[#f4efe2]" style={{ aspectRatio: '1535 / 1024' }}>
                                            <img alt="Heat-Resistant FR Wires" fetchPriority="auto" loading="lazy" decoding="async" data-nimg="fill" className="h-full w-full object-contain" style={{ width: '100%', height: '100%', objectFit: 'contain', objectPosition: '50% 50%', color: 'transparent' }} sizes="(max-width: 768px) 85vw, (max-width: 1280px) 55vw, 42vw" src={img8} />
                                        </div>
                                        <div className="flex flex-col gap-3 px-1">
                                            <h3 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-heading-sm-font-size)', '--typography-font-weight': 'var(--typography-heading-sm-font-weight)', '--typography-line-height': 'var(--typography-heading-sm-line-height)', '--typography-letter-spacing': 'var(--typography-heading-sm-letter-spacing)', '--typography-font-family': 'var(--typography-heading-sm-font-family)', color: '#060603' }}>Heat-Resistant FR Wires</h3>
                                            <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#1b1b16' }}>Specialized FR wires designed to withstand high temperatures while maintaining optimal electrical performance.</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-col gap-5">
                                        <div className="overflow-hidden rounded-[28px] bg-[#f4efe2]" style={{ aspectRatio: '1535 / 1024' }}>
                                            <img alt="Flexible Twin Twisted Wires" fetchPriority="auto" loading="lazy" decoding="async" data-nimg="fill" className="h-full w-full object-contain" style={{ width: '100%', height: '100%', objectFit: 'contain', objectPosition: '50% 50%', color: 'transparent' }} sizes="(max-width: 768px) 85vw, (max-width: 1280px) 55vw, 42vw" src={img9} />
                                        </div>
                                        <div className="flex flex-col gap-3 px-1">
                                            <h3 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-heading-sm-font-size)', '--typography-font-weight': 'var(--typography-heading-sm-font-weight)', '--typography-line-height': 'var(--typography-heading-sm-line-height)', '--typography-letter-spacing': 'var(--typography-heading-sm-letter-spacing)', '--typography-font-family': 'var(--typography-heading-sm-font-family)', color: '#060603' }}>Flexible Twin Twisted Wires</h3>
                                            <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#1b1b16' }}>Flexible twin twisted wires ideal for appliances, lighting, and temporary electrical setups.</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-col gap-5">
                                        <div className="overflow-hidden rounded-[28px] bg-[#f4efe2]" style={{ aspectRatio: '1535 / 1024' }}>
                                            <img alt="Low-Loss Coaxial Cables" fetchPriority="auto" loading="lazy" decoding="async" data-nimg="fill" className="h-full w-full object-contain" style={{ width: '100%', height: '100%', objectFit: 'contain', objectPosition: '50% 50%', color: 'transparent' }} sizes="(max-width: 768px) 85vw, (max-width: 1280px) 55vw, 42vw" src={img10} />
                                        </div>
                                        <div className="flex flex-col gap-3 px-1">
                                            <h3 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-heading-sm-font-size)', '--typography-font-weight': 'var(--typography-heading-sm-font-weight)', '--typography-line-height': 'var(--typography-heading-sm-line-height)', '--typography-letter-spacing': 'var(--typography-heading-sm-letter-spacing)', '--typography-font-family': 'var(--typography-heading-sm-font-family)', color: '#060603' }}>Low-Loss Coaxial Cables</h3>
                                            <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#1b1b16' }}>Advanced coaxial cables engineered for high signal strength and minimal transmission loss.</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-col gap-5">
                                        <div className="overflow-hidden rounded-[28px] bg-[#f4efe2]" style={{ aspectRatio: '1535 / 1024' }}>
                                            <img alt="Specialized Automotive Wires" fetchPriority="auto" loading="lazy" decoding="async" data-nimg="fill" className="h-full w-full object-contain" style={{ width: '100%', height: '100%', objectFit: 'contain', objectPosition: '50% 50%', color: 'transparent' }} sizes="(max-width: 768px) 85vw, (max-width: 1280px) 55vw, 42vw" src={img11} />
                                        </div>
                                        <div className="flex flex-col gap-3 px-1">
                                            <h3 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-heading-sm-font-size)', '--typography-font-weight': 'var(--typography-heading-sm-font-weight)', '--typography-line-height': 'var(--typography-heading-sm-line-height)', '--typography-letter-spacing': 'var(--typography-heading-sm-letter-spacing)', '--typography-font-family': 'var(--typography-heading-sm-font-family)', color: '#060603' }}>Specialized Automotive Wires</h3>
                                            <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#1b1b16' }}>Durable automotive wires built to handle heat, vibration, and demanding vehicle environments.</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-col gap-5">
                                        <div className="overflow-hidden rounded-[28px] bg-[#f4efe2]" style={{ aspectRatio: '1535 / 1024' }}>
                                            <img alt="Submersible Pump Cables" fetchPriority="auto" loading="lazy" decoding="async" data-nimg="fill" className="h-full w-full object-contain" style={{ width: '100%', height: '100%', objectFit: 'contain', objectPosition: '50% 50%', color: 'transparent' }} sizes="(max-width: 768px) 85vw, (max-width: 1280px) 55vw, 42vw" src={img12} />
                                        </div>
                                        <div className="flex flex-col gap-3 px-1">
                                            <h3 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-heading-sm-font-size)', '--typography-font-weight': 'var(--typography-heading-sm-font-weight)', '--typography-line-height': 'var(--typography-heading-sm-line-height)', '--typography-letter-spacing': 'var(--typography-heading-sm-letter-spacing)', '--typography-font-family': 'var(--typography-heading-sm-font-family)', color: '#060603' }}>Submersible Pump Cables</h3>
                                            <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#1b1b16' }}>Water-resistant cables designed for reliable underwater performance in pumps and deep well systems.</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-col gap-5">
                                        <div className="overflow-hidden rounded-[28px] bg-[#f4efe2]" style={{ aspectRatio: '1535 / 1024' }}>
                                            <img alt="Extra-Flexible Welding Cables" fetchPriority="auto" loading="lazy" decoding="async" data-nimg="fill" className="h-full w-full object-contain" style={{ width: '100%', height: '100%', objectFit: 'contain', objectPosition: '50% 50%', color: 'transparent' }} sizes="(max-width: 768px) 85vw, (max-width: 1280px) 55vw, 42vw" src={img13} />
                                        </div>
                                        <div className="flex flex-col gap-3 px-1">
                                            <h3 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-heading-sm-font-size)', '--typography-font-weight': 'var(--typography-heading-sm-font-weight)', '--typography-line-height': 'var(--typography-heading-sm-line-height)', '--typography-letter-spacing': 'var(--typography-heading-sm-letter-spacing)', '--typography-font-family': 'var(--typography-heading-sm-font-family)', color: '#060603' }}>Extra-Flexible Welding Cables</h3>
                                            <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#1b1b16' }}>Highly flexible welding cables built for heavy-duty usage with strong insulation and durability.</p>
                                        </div>
                                    </div>
                                    <div className="flex flex-col gap-5">
                                        <div className="overflow-hidden rounded-[28px] bg-[#f4efe2]" style={{ aspectRatio: '1535 / 1024' }}>
                                            <img alt="UV-Resistant Solar PV Cables" fetchPriority="auto" loading="lazy" decoding="async" data-nimg="fill" className="h-full w-full object-contain" style={{ width: '100%', height: '100%', objectFit: 'contain', objectPosition: '50% 50%', color: 'transparent' }} sizes="(max-width: 768px) 85vw, (max-width: 1280px) 55vw, 42vw" src={img14} />
                                        </div>
                                        <div className="flex flex-col gap-3 px-1">
                                            <h3 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-heading-sm-font-size)', '--typography-font-weight': 'var(--typography-heading-sm-font-weight)', '--typography-line-height': 'var(--typography-heading-sm-line-height)', '--typography-letter-spacing': 'var(--typography-heading-sm-letter-spacing)', '--typography-font-family': 'var(--typography-heading-sm-font-family)', color: '#060603' }}>UV-Resistant Solar PV Cables</h3>
                                            <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#1b1b16' }}>Weatherproof solar cables designed for long-lasting performance in solar panel installations.</p>
                                        </div>
                                    </div>
                                </div>
                                <div className="flex gap-3 @tablet:hidden">
                                    <button type="button" disabled="" aria-label="Previous" style={{ '--bg-color': 'rgba(0%, 0%, 0%, 0.04764)', '--hover-bg-color': '#e0d9c8' }} className="appearance-none text-inherit bg-(--bg-color) hover:bg-(--hover-bg-color) cursor-pointer p-3 disabled:opacity-50 rounded-3xl"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20" width="24" height="24" className="size-5" style={{ color: '#000' }}><path fill="currentColor" fillRule="evenodd" d="M12.707 5.293a1 1 0 0 1 0 1.414L9.414 10l3.293 3.293a1 1 0 0 1-1.414 1.414l-4-4a1 1 0 0 1 0-1.414l4-4a1 1 0 0 1 1.414 0" clipRule="evenodd"></path></svg></button>
                                    <button type="button" disabled="" aria-label="Next" style={{ '--bg-color': 'rgba(0%, 0%, 0%, 0.04764)', '--hover-bg-color': '#e0d9c8' }} className="appearance-none text-inherit bg-(--bg-color) hover:bg-(--hover-bg-color) cursor-pointer p-3 disabled:opacity-50 rounded-3xl"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20" width="24" height="24" className="size-5" style={{ color: '#000' }}><path fill="currentColor" fillRule="evenodd" d="M7.293 14.707a1 1 0 0 1 0-1.414L10.586 10 7.293 6.707a1 1 0 0 1 1.414-1.414l4 4a1 1 0 0 1 0 1.414l-4 4a1 1 0 0 1-1.414 0" clipRule="evenodd"></path></svg></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div className="w-full" id="कॉल टू एक्शन">
                <section className="w-full relative" style={{ contain: 'layout style paint' }}>
                    <div className="relative" style={{ paddingBottom: '488px' }}>
                        <div className="absolute inset-0" style={{ borderRadius: 'inherit', background: 'linear-gradient(180deg, transparent 0%, transparent 100%), #0F0F0079' }}></div>
                        <div className="relative mx-auto max-w-[1536px] px-6 flex flex-col gap-4 py-16 @tablet:py-24 items-center justify-center text-center" style={{ zIndex: '10' }}>
                            <div className="flex flex-col max-w-2xl items-center">
                                <h2 className="[font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-display-md-font-size)', '--typography-font-weight': 'var(--typography-display-md-font-weight)', '--typography-line-height': 'var(--typography-display-md-line-height)', '--typography-letter-spacing': 'var(--typography-display-md-letter-spacing)', '--typography-font-family': 'var(--typography-display-md-font-family)', color: '#f9f9f2' }}>
                                    Get Reliable Electrical Wiring Solutions Today
                                </h2>
                            </div>
                            <div className="flex flex-col max-w-2xl gap-8">
                                <p className="whitespace-pre-line [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-md-font-size)', '--typography-font-weight': 'var(--typography-body-md-font-weight)', '--typography-line-height': 'var(--typography-body-md-line-height)', '--typography-letter-spacing': 'var(--typography-body-md-letter-spacing)', '--typography-font-family': 'var(--typography-body-md-font-family)', color: '#e5e6de' }}>
                                    Partner with Electra Wires for high-quality electrical wires, FR cables, and industrial solutions tailored to your needs.
                                </p>
                                <div className="grid grid-cols-1 gap-4 @tablet:flex @tablet:flex-row items-center @tablet:justify-center">
                                    <Link data-slot="button" label="Get in Touch" style={{ '--bg-color': '#E8A317', '--hover-bg-color': '#da990f', color: '#000' }} className="inline-flex shrink-0 cursor-pointer items-center justify-center bg-(--bg-color) whitespace-nowrap transition-all outline-none hover:bg-(--hover-bg-color) focus-visible:border-primary-border focus-visible:ring-[3px] focus-visible:ring-primary-interactive-bg disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-error-border aria-invalid:ring-error-interactive-bg [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*=&#x27;size-&#x27;])]:size-4 border border-(--bg-color) hover:border-(--hover-bg-color) gap-2 px-5 py-2.5 has-[>svg:first-child]:pr-4 has-[>svg:last-child]:pl-4 has-[>svg:only-child]:px-2.5 rounded-3xl" to="/contact">
                                        <span className="min-w-0 overflow-hidden text-ellipsis [font-family:var(--typography-font-family)] [font-size:var(--typography-font-size)] leading-(--typography-line-height) font-(--typography-font-weight) tracking-(--typography-letter-spacing)" style={{ '--typography-font-size': 'var(--typography-body-sm-em-font-size)', '--typography-font-weight': 'var(--typography-body-sm-em-font-weight)', '--typography-line-height': 'var(--typography-body-sm-em-line-height)', '--typography-letter-spacing': 'var(--typography-body-sm-em-letter-spacing)', '--typography-font-family': 'var(--typography-body-sm-em-font-family)', color: '#000' }}>Get in Touch</span>
                                    </Link>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </main>
    );
};

export default Products;
